---
title: "Purple Urchin Removal Maps"
subtitle: "By Gina Contolini. Gina.Contolini@noaa.gov"
author: "Greater Farallones Association and Greater Farallones and Cordell Bank National Marine Sanctuaries"
date: "Updated on `r Sys.Date()`"
output: 
  pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(ggOceanMaps)
library(tidyverse)
library(ggspatial)
library(usethis)
library(marmap) # for raster bathymetry
library(stars) # for raster bathymetry
library(sf) # for raster bathymetry and high res downloaded shapefiles

# load coordinates to plot
removal_coords <- read_csv('Purple urchin landings datasheet - removal_coords.csv')

# #high res coastline data.
## Following instructions from ggOceanMaps user guide. https://mikkovihtakari.github.io/ggOceanMaps/articles/ggOceanMaps.html 
## Download large files of high res imagery here: https://www.naturalearthdata.com/downloads/10m-physical-vectors/ 

NEDPath <- "C:/Users/Gina.Contolini/Documents/GFA Kelp Restoration/GIS"
# coastline <- rgdal::readOGR(paste(NEDPath, "ne_10m_coastline.shp", sep = '/'))
## Please note that **rgdal** will be retired during 2023, plan transition to sf/stars/terra functions using GDAL and PROJ at your earliest convenience (see https://r-spatial.org/r/2023/05/15/evolution4.html and earlier blogs for guidance).
# Maybe this site will help: https://gis.stackexchange.com/questions/460615/using-a-downloaded-shapefile-in-ggplot2-and-r-readogr-error
my_sf <- sf::st_read(file.path(NEDPath, 'ne_10m_coastline.shp'))
plot(sf::st_geometry(my_sf))

ggplot(my_sf) +
  geom_sf()

# Create folder for high-resolution shapefiles downloaded from ggOceanMapsLargeData
## usethis::edit_r_profile() and then I pasted .ggOceanMapsenv <- new.env() and .ggOceanMapsenv$datapath <- '~/ggOceanMapsLargeData' into the file ".Rprofile"

# Example of how to get raster bathymetry
dt <- data.frame(lon = c(-117, -117, -116, -116), lat = c(30, 31, 31, 30))

limits <- auto_limits(dt, expand.factor = 1.1)$projLimits
bm <- basemap(data = dt)

mar_bathy <- marmap::getNOAA.bathy(resolution = 0.01, lon1 = limits["xmin"], lon2 = limits["xmax"], lat1 = limits["ymin"], lat2 = limits["ymax"])

bathy <- raster_bathymetry(stars::st_as_stars(marmap::as.raster(mar_bathy)), depths = NULL)

p <- bm + 
  stars::geom_stars(data = bathy$raster) +
  ggplot2::scale_fill_gradientn(
    name = "Depth (m)", breaks = seq(0,5e3,1e3), limits = c(0,NA), 
    colors = colorRampPalette(c("#F7FBFF", "#DEEBF7", "#9ECAE1", "#4292C6", "#08306B"))(100)
  )

reorder_layers(p)

```

```{r Fort Ross Cove}
frc = c(-123.255, -123.2399, 38.505, 38.515)
# the map:
basemap(limits = frc) +
  ggspatial::geom_spatial_point(data = removal_coords %>% filter(!site == 'timber'), aes(x = lon, y = lat, shape = vessel, color = vessel)) +
  geom_point() +
  scale_color_manual(values = c('green4', 'navyblue')) +
  scale_y_continuous(breaks = seq(38.505, 38.515, 0.005)) +
  scale_x_continuous(breaks = seq(-123.255, -123.240, 0.005)) +
  theme(panel.grid = element_blank()) +
  ggspatial::annotation_scale() + # adds scale bar
  ggtitle('Purple urchin removals Fort Ross Cove 2023') 

limits_frc <- auto_limits(removal_coords %>% select(lat, lon), expand.factor = 1.1)$projLimits
bm_frc <- basemap(data = removal_coords)

mar_bathy <- marmap::getNOAA.bathy(resolution = .01, lon1 = limits_frc["xmin"], lon2 = limits_frc["xmax"], lat1 = limits_frc["ymin"], lat2 = limits_frc["ymax"])

bathy <- raster_bathymetry(stars::st_as_stars(marmap::as.raster(mar_bathy)), depths = NULL)

frc_bathy <- bm_frc + 
  stars::geom_stars(data = bathy$raster) +
  ggplot2::scale_fill_gradientn(
    name = "Depth (m)", breaks = seq(0,5e3,1e3), limits = c(0,NA), 
    colors = colorRampPalette(c("#F7FBFF", "#DEEBF7", "#9ECAE1", "#4292C6", "#08306B"))(100)
    )

reorder_layers(frc_bathy)

```

```{r Timber Cove}
tc = c(-123.280, -123.26499, 38.535, 38.525)
basemap(limits = tc) +
  ggspatial::geom_spatial_point(data = removal_coords %>% filter(!site == 'fort_ross'), aes(x = lon, y = lat), color = 'red3') +
  geom_point() +
  scale_y_continuous(breaks = seq(38.525, 38.535, 0.005)) +
  scale_x_continuous(breaks = seq(-123.280, -123.265, 0.005)) +
  theme(panel.grid = element_blank()) +
  ggspatial::annotation_scale() +
  ggtitle('Purple urchin removals Timber Cove 2023')
```

This report was produced using RMarkdown in RStudio version 2023.09.1+494 "Desert Sunflower" and `r version$version.string`. Maps were produced using package 'ggOceanMaps': Vihtakari M (2023). _ggOceanMaps: Plot Data on Oceanographic Maps using 'ggplot2'_. R package version 2.1.1, <https://CRAN.R-project.org/package=ggOceanMaps>.