---
title: "NMDS_swath_upc"
author: "Gina Contolini"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.keep = 'all'
)

#### Install and load packages ####
library(car) #companion to applied regression
library(tidyverse) # all tidyverse packages including tidyr, dplyr, and ggplot2
library(ggpubr) # plot aesthetics
library(flextable) # tidy display table package
library(vegan)
library(scales) # for color palette

#### Create plot theme ####
theme_set(theme( 
   panel.background = element_blank(), # remove panel background
   # panel.grid.minor.x = element_blank(), # remove minor x axis grid line
   # panel.grid.major.x = element_blank(), # remove major x axis grid line
   panel.grid = element_blank(), # remove all grid lines
   axis.text = element_text(size = 13,color = 'black'), #makes axis labels bigger
   axis.title = element_text(size = 15), #makes axis title bigger and bold
   # axis.ticks = element_blank(),
   # axis.title.y = element_text(margin=margin(0,10,0,5)), #pushes the y axis title away from the y axis labels
   # axis.text.x = element_text(margin=margin(0,0,20,0)), #pushes the x axis title away from the x axis labels and pushes the bars down closer to the x axis labels
   legend.title = element_text(size = 16),
   legend.text  = element_text(size = 16),
   legend.background = element_blank(),
   panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5), # border around the whole plot
   plot.title = element_text(size = 15)
   #legend.key = element_blank()
))

# fig theme with big text for presentation
pres_theme <- 
  theme(
    axis.text = element_text(size = 20),
    axis.title = element_text(size = 24),
    legend.title = element_text(size = 24), 
    legend.text = element_text(size = 20)
  )

# Okabe-Ito color palette
okabeito <- c('#56B4E9', '#009E73', '#f0E442', '#E69F00') #https://datavizf24.classes.andrewheiss.com/resource/colors.html
viridis <- pal_viridis(begin = 0, end = 1)(4)
```

```{r Load curated data}
# this data is the result of much scuplting from subtidal_swath.Rmd and UPC_surveys.Rmd

PISCO_all <- read_csv('PISCO_2021-2025.csv')
PISCO_all$site[which(PISCO_all$site == 'Fort Ross')] = 'Fort_Ross' # remove space in Fort Ross

PISCO_all_ms <- PISCO_all %>% 
  mutate(site = as.factor(site)) %>% 
  filter(site %in% c('Fort_Ross', 'Timber', 'Ocean', 'Gerstle')) %>% 
  filter(year %in% c(2021, 2022, 2024, 2025)) %>% 
  mutate(site = factor(site, levels = c('Fort_Ross', 'Timber', 'Gerstle', 'Ocean')))

PISCO_bio_ms <- PISCO_all_ms %>% 
  filter(!classcode %in% c("BEDRK", "BOULD", "SAND", "COB", '0-10cm', '10cm-1m', '1m-2m', '>2m', 'BARROC', 'BARSAN', 'DEADHOLD', 'SHELL')) #Remove things that aren't species. 

```

# Multivariate analyses using all swath and UPC surveys combined. 
```{r set up and run metaMDS all swath and UPC}
################ much of below is copied from subtidal_swath.Rmd ################  
### and now I attempt to do the same analysis with this fuller dataset that includes UPC observations ###

# check if each transect ID has a all types of surveys done. so check for strpur, nerlue, ptecalad, atmin, bedrk, 10cm-1m. 
PISCO_all_ms %>% 
  filter(classcode %in% c('STRPUR', 'NERLUE', 'PATMIN', 'PTECALAD', 'BEDRK', '10cm-1m')) %>% 
  count(year, site, transect_ID) %>% 
  filter(!n == 6) #lookin good. the ones with only 5 obseravtions just didn't have a UPC classcode since I didn't include implicit zeros for those yet.

PISCO_all_ms %>%
  count(transect_ID, classcode) %>%
  filter(n > 1)

# Reformatting the data frame for the analysis. cols need to be classcodes.
PISCO_all_ms_matrix <- PISCO_all_ms %>% 
  select(transect_ID, classcode, observations) %>% 
  # I want each col to be a classcode, rows to be IDs, and values to be observations.
  pivot_wider(names_from = 'classcode', values_from = 'observations') %>% 
  replace(is.na(.), 0) %>% # make any NA value into 0.
  as.data.frame()

PISCO_all_ms_matrix$transect_ID = NULL # remove transect_ID column

## Convert absolute abundance to relative abundance to standardize
PISCO_all_ms_matrix_decostand <- decostand(PISCO_all_ms_matrix, method = 'total') # 78 rows.

set.seed(19918) # set seed to make sure the metaMDS repeats a best solution.
PISCO_all_ms_MDS1 <- metaMDS(PISCO_all_ms_matrix_decostand, distance = 'bray') # stress value should be between 0 and 0.2 according to https://jkzorz.github.io/2019/06/06/NMDS.html.# My stress value is 0.07.

## reformat so it can be plotted in ggplot with groupings.
PISCO_all_ms_data_scores <- as.data.frame(scores(PISCO_all_ms_MDS1)$sites)

## Add back identifier columns
PISCO_all_ms_data_scores$transect_ID = unique(PISCO_all_ms$transect_ID) 

# i want to join this with the sites and dates and stuff.
PISCO_all_ms_sites <- PISCO_all_ms %>%
  dplyr::select(transect_ID, site, year, month, day) # just these cols
dim(PISCO_all_ms_sites) # check dimensions. 5643 rows. remove duplicates for the join.
PISCO_all_ms_sites_distinct <- distinct(PISCO_all_ms_sites) # 78 rows. good to go.

PISCO_all_ms_NMDS_sites <- dplyr::inner_join(PISCO_all_ms_data_scores, PISCO_all_ms_sites_distinct, by = 'transect_ID') %>% 
  mutate(year = as.factor(year))
rownames(PISCO_all_ms_matrix_decostand) = paste(PISCO_all_ms_NMDS_sites$site, PISCO_all_ms_NMDS_sites$transect_ID)
```

```{r fig.cap = 'Community dissimilarities (Bray-Curtis) among subtidal swath and all UPC transects. Species vectors shown for significant species only (P < 0.05)'}
# Prepping the species vectors
spp_fit <- envfit(PISCO_all_ms_MDS1, PISCO_all_ms_matrix_decostand, permutations = 999) # there were 50+ warnings bc SD = 0.
spp_scores <- as.data.frame(scores(spp_fit, display = 'vectors'))
spp_scores <- cbind(spp_scores, species = rownames(spp_scores))
spp_scores <- cbind(spp_scores, pval = spp_fit$vectors$pvals)
sig_spp_scores <- subset(spp_scores, pval <= 0.05) %>% arrange(pval) # this is where it filters for P <= 0.05
sig_spp_scores$site = 'Timber' # just put one so it plots
sig_spp_scores$year = '2022' # just put one so it plots
# reposition the overlapping species labels
sig_spp_scores$NMDS1_label = sig_spp_scores$NMDS1
sig_spp_scores$NMDS2_label = sig_spp_scores$NMDS2
# sig_spp_scores$NMDS1_label[which(sig_spp_scores$species == 'LAMREC')] = 0.65 # format for readjusting labels

ggplot(PISCO_all_ms_NMDS_sites, aes(x = NMDS1, y = NMDS2, color = site, shape = year)) +
  stat_ellipse() +
  # annotate('text', x = 2, y = 1.2, label = paste('Stress =', round(PISCO_all_ms_MDS1$stress, digits = 3))) +
  ggtitle('Swath and UPC community dissimilarities') +
  geom_segment(data = sig_spp_scores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), color = 'grey80', arrow = arrow(length = unit(0.2, "cm")), lwd = 0.3) +
  geom_point(size = 3, alpha = 0.7) +
  annotate('text', size = 3, x = sig_spp_scores$NMDS1_label, y = sig_spp_scores$NMDS2_label, label = sig_spp_scores$species, color = 'grey60') +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12))

```

```{r SIMPER analysis swath and all UPC}
# Which species are most responsible for any community differences observed? Calculate discriminating species between two groups using BC dissimilarities.
PISCO_all_ms_simper <- simper(PISCO_all_ms_matrix_decostand, group = PISCO_all_ms_NMDS_sites$site)
summary(PISCO_all_ms_simper)
PISCO_all_ms_simper

# The top contributors are:
## STRPUR for all contrasts
## BEDRK and 10cm-1m for 2nd place overall
## >2, BEDRK, 10cm-1m in 3rd place overall
## ENCRED, BEDRK, >2 in 4th place
## BOULD, ENCRED in 5th place

# Contrasts I care most about:
# FR Cove vs. Timber Cove
summary(PISCO_all_ms_simper)[1]$`Fort Ross_Timber` %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("FRC vs TC")

  flextable::set_caption("FRC vs TC")

# FRC vs GC
summary(PISCO_all_ms_simper)[3]$`Fort Ross_Gerstle` %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("FRC vs GC")
  
# Timber Cove vs. Ocean Cove
summary(PISCO_all_ms_simper)[4]$Timber_Ocean %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("TC vs OC")


```

```{r PERMANOVA, ANOSIM, all swath and UPC}

```

# Multivariate analyses using swath and just biotic UPC points combined.
```{r set up and run metaMDS swath and bio UPC}
# check if each transect ID has a all types of surveys done. so check for strpur, nerlue, ptecalad, atmin, bedrk, 10cm-1m.

PISCO_bio_ms %>% 
  filter(classcode %in% c('STRPUR', 'NERLUE', 'PATMIN', 'PTECALAD')) %>% 
  count(year, site, transect_ID) %>% 
  filter(!n == 4) #lookin good. 

PISCO_bio_ms %>%
  count(transect_ID, classcode) %>%
  filter(n > 1) # none have more than one.

# simple figure showing sample sizes
PISCO_bio_ms %>% 
  count(year, site, transect_ID) %>% 
  count(year, site) %>% 
  ggplot(aes(x = year, y = n, color = site)) +
  scale_color_manual(values = viridis) + # Okabeito color palette . https://datavizf24.classes.andrewheiss.com/resource/colors.html
  # scale_color_discrete(palette = 'viridis') + # viridis color palette option
  geom_point(size = 7, position = position_dodge(0.2)) +
  geom_line(size = 1.5, position = position_dodge(0.2)) +
  labs(y = 'Number of transects', x = 'Year') +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 2)) +
  pres_theme
  
#### limit to just years we have control data ####
PISCO_bio_ms <- PISCO_bio_ms %>%
  filter(year %in% c('2024', '2025')) # just the years we have control data. Remove this part if you are trying to consider all years.
########

# Reformatting the data frame for the analysis. cols need to be classcodes.
PISCO_bio_ms_matrix <- PISCO_bio_ms %>% 
  select(transect_ID, classcode, observations) %>% 
  # I want each col to be a classcode, rows to be IDs, and values to be observations.
  pivot_wider(names_from = 'classcode', values_from = 'observations') %>% 
  replace(is.na(.), 0) %>% # make any NA value into 0.
  as.data.frame()

PISCO_bio_ms_matrix$transect_ID = NULL # remove transect_ID column

## Convert absolute abundance to relative abundance to standardize
# Aren't they already standardized? I mean they're all in number per m2. That feels standardized. Well Maria says to do this.
PISCO_bio_ms_matrix_decostand <- decostand(PISCO_bio_ms_matrix, method = 'total') # 78 rows. total divides everything by row totals. 
# calculate distances? or is that done in the metaMDS? 
# avgdist(sample = PISCO_bio_ms_matrix_decostand) # calculates bray-curtis distances a set number of times and reports the average.

set.seed(1917678) # set seed to make sure the metaMDS repeats a best solution.
PISCO_bio_ms_MDS1 <- metaMDS(PISCO_bio_ms_matrix_decostand, distance = 'bray') # stress value should be between 0 and 0.2 according to https://jkzorz.github.io/2019/06/06/NMDS.html.# My stress value is 0.15

## reformat so it can be plotted in ggplot with groupings.
PISCO_bio_ms_data_scores <- as.data.frame(scores(PISCO_bio_ms_MDS1)$sites)

## Add back identifier columns
PISCO_bio_ms_data_scores$transect_ID = unique(PISCO_bio_ms$transect_ID) 

# i want to join this with the sites and dates and stuff.
PISCO_bio_ms_sites <- PISCO_bio_ms %>%
  dplyr::select(transect_ID, site, year, month, day) # just these cols
dim(PISCO_bio_ms_sites) # check dimensions. 5184 rows. remove duplicates for the join.
PISCO_bio_ms_sites_distinct <- distinct(PISCO_bio_ms_sites) 

PISCO_bio_ms_NMDS_sites <- dplyr::inner_join(PISCO_bio_ms_data_scores, PISCO_bio_ms_sites_distinct, by = 'transect_ID') %>% 
  mutate(year = as.factor(year))
rownames(PISCO_bio_ms_matrix_decostand) = paste(PISCO_bio_ms_NMDS_sites$site, PISCO_bio_ms_NMDS_sites$transect_ID)
```

```{r fig.cap = 'Community dissimilarities (Bray-Curtis) among subtidal swath and UPC transects with just biological points. Species vectors shown for significant species only (P < 0.05)'}
# Prepping the species vectors
spp_fit <- envfit(PISCO_bio_ms_MDS1, PISCO_bio_ms_matrix_decostand, permutations = 999) # there were 50+ warnings bc SD = 0.
spp_scores <- as.data.frame(scores(spp_fit, display = 'vectors'))
spp_scores <- cbind(spp_scores, species = rownames(spp_scores))
spp_scores <- cbind(spp_scores, pval = spp_fit$vectors$pvals)
sig_spp_scores <- subset(spp_scores, pval <= 0.05) %>% arrange(pval) # this is where it filters for P <= 0.05
sig_spp_scores$site = 'Timber' # just put one so it plots
sig_spp_scores$year = '2024' # just put one so it plots
# reposition the overlapping species labels
sig_spp_scores$NMDS1_label = sig_spp_scores$NMDS1
sig_spp_scores$NMDS2_label = sig_spp_scores$NMDS2
# sig_spp_scores$NMDS1_label[which(sig_spp_scores$species == 'LAMREC')] = 0.65 # format for readjusting labels

# PERMANOVA
str(as.dist(PISCO_bio_ms_matrix_decostand)) # make sure the response is a distance matrix (type 'dist'). it's a dataframe.
adonis2(PISCO_bio_ms_matrix_decostand ~
                                 PISCO_bio_ms_NMDS_sites$site *
                                 PISCO_bio_ms_NMDS_sites$year +
                        PISCO_bio_ms_NMDS_sites$site/PISCO_bio_ms_NMDS_sites$transect_ID,
                        by = 'terms') 

PISCO_bio_ms_adonis <- adonis2(PISCO_bio_ms_matrix_decostand ~ site * year, 
                               strata = PISCO_bio_ms_NMDS_sites$site, # accounts for transects nested in sites
                        data = PISCO_bio_ms_NMDS_sites,
                        by = 'terms') 

# Check if dispersions are similar
site_disper <- betadisper(vegdist(PISCO_bio_ms_matrix_decostand), group = PISCO_bio_ms_NMDS_sites$site) 
anova(site_disper) # tests if the dispersion is sig dif by site. P = 0.03.

year_disper <- betadisper(vegdist(PISCO_bio_ms_matrix_decostand), group = PISCO_bio_ms_NMDS_sites$year) 
anova(year_disper) p = 0.2


ggplot(PISCO_bio_ms_NMDS_sites, aes(x = NMDS1, y = NMDS2, color = site, shape = year)) +
  stat_ellipse() +
  annotate('text', x = 1.5, y = 1.2, label = paste('Stress =', round(PISCO_bio_ms_MDS1$stress, digits = 3))) +
  # ggtitle('Swath and UPC community dissimilarities') +
  geom_segment(data = sig_spp_scores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), color = 'grey80', arrow = arrow(length = unit(0.2, "cm")), lwd = 0.3) +
  geom_point(size = 5, alpha = 0.7) +
  annotate('text', size = 3, x = sig_spp_scores$NMDS1_label, y = sig_spp_scores$NMDS2_label, label = sig_spp_scores$species, color = 'grey60') +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12)) +
  scale_color_manual(values = viridis) +
  pres_theme

# NMDS plot with just some sites
ggplot(PISCO_bio_ms_NMDS_sites %>% filter(site %in% c('Fort_Ross')), aes(x = NMDS1, y = NMDS2, color = site, shape = year)) +
  stat_ellipse() +
  # annotate('text', x = 2, y = 1.2, label = paste('Stress =', round(PISCO_bio_ms_MDS1$stress, digits = 3))) +
  # ggtitle('Swath and UPC community dissimilarities') +
  geom_segment(data = sig_spp_scores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), color = 'grey80', arrow = arrow(length = unit(0.2, "cm")), lwd = 0.3) +
  geom_point(size = 5, alpha = 0.7) +
  annotate('text', size = 3, x = sig_spp_scores$NMDS1_label, y = sig_spp_scores$NMDS2_label, label = sig_spp_scores$species, color = 'grey60') +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12)) +
  scale_color_manual(values = viridis[1]) +
  pres_theme
```

```{r SIMPER analysis swath and bio UPC}
# Which species are most responsible for any community differences observed? Calculate discriminating species between two groups using BC dissimilarities.
PISCO_bio_ms_simper <- simper(PISCO_bio_ms_matrix_decostand, group = PISCO_bio_ms_NMDS_sites$site)
summary(PISCO_bio_ms_simper)
PISCO_bio_ms_simper

# The top contributors are:
## STRPUR always in top 2
## ENCRED always in top 2
## CRUCOR 
## BARSAN
## BARROC
## DESSPP
## BARNAC
## PTECALAD

# Contrasts I care most about:
# FR Cove vs. Timber Cove
summary(PISCO_bio_ms_simper)[1]$Fort_Ross_Timber %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("FRC vs TC")

  flextable::set_caption("FRC vs TC")

# FRC vs GC
summary(PISCO_bio_ms_simper)[3]$Fort_Ross_Gerstle %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("FRC vs GC")
  
# Timber Cove vs. Ocean Cove
summary(PISCO_bio_ms_simper)[4]$Timber_Ocean %>% 
  round(digits = 4) %>% 
  slice_head(n = 10) %>% 
  rownames_to_column() %>% 
  flextable() %>% 
  flextable::set_caption("TC vs OC")

# make the result into a dataframe for easy manipulations
simper.tidy <- function(simper.summary.object, comparisons) {
  simper.results <- c()
    for(i in 1:length(comparisons)) {
      require(tidyverse)
      temp <- simper.summary.object[as.character(comparisons[i])] |>
      as.data.frame()
      colnames(temp) <- gsub(
        paste(comparisons[i],".", sep = ""), "", colnames(temp))
      temp <- temp |>
        mutate(Comparison = comparisons[i],
          Position = row_number()) |>
        rownames_to_column(var = "Species")
    simper.results <- rbind(simper.results, temp)
    }
simper.results
  }

comparisons <- c('Fort_Ross_Timber', 'Fort_Ross_Gerstle', 'Timber_Ocean', 'Fort_Ross_Ocean', 'Timber_Gerstle', 'Ocean_Gerstle')
PISCO_bio_ms_simper_results <- simper.tidy(simper.summary.object = PISCO_bio_ms_simper, comparisons = comparisons)

PISCO_bio_ms_simper_results %>% 
  filter(p <= 0.05) %>% 
  arrange(desc(average))
  # count(Comparison) # which pair comparison has the most significant differences? maybe this pair are the most different. FRC vs. Tc. 


# Summarize the average differences among each pair.
PISCO_bio_ms_simper_results %>% 
  group_by(Comparison) %>% 
  summarise(sum_average = sum(average), sum_sd = sd(average)) %>% 
  ggplot(aes(x = Comparison, y = sum_average)) +
  geom_errorbar(aes(ymin = sum_average - sum_sd, ymax = sum_average + sum_sd, width = 0)) +
  geom_point(size = 6) +
  pres_theme + theme(axis.text.x = element_text(size = 15))

# PERMANOVA
PISCO_bio_ms_adonis <- adonis2(PISCO_bio_ms_matrix_decostand ~ PISCO_bio_ms_NMDS_sites$site * PISCO_bio_ms_NMDS_sites$year, by = 'terms') # might need to add nesting term? 1|site:transect_ID ???
```

# Site specific analyses
```{r one site only; nmds, permanova, simper}
PISCO_bio_ms <- PISCO_all_ms %>% 
  filter(!classcode %in% c("BEDRK", "BOULD", "SAND", "COB", '0-10cm', '10cm-1m', '1m-2m', '>2m', 'BARROC', 'BARSAN', 'DEADHOLD', 'SHELL')) #Remove things that aren't species. 
##### Set the site you want #######
select_site = 'Timber'
####################################

# How did a single restoration site change over time?
## create dissimilarity matrix for Fort Ross only.

PISCO_bio_site <- PISCO_bio_ms %>%
  filter(site == select_site) %>% 
  mutate(year = as.factor(year))

PISCO_bio_site_matrix <- PISCO_bio_site %>% 
  select(transect_ID, classcode, observations) %>% 
  # I want each col to be a classcode, rows to be IDs, and values to be observations.
  pivot_wider(names_from = 'classcode', values_from = 'observations') %>% 
  replace(is.na(.), 0) %>% # make any NA value into 0.
  as.data.frame()

PISCO_bio_site_matrix$transect_ID = NULL # remove transect_ID column

## Convert absolute abundance to relative abundance to standardize
PISCO_bio_site_matrix_decostand <- decostand(PISCO_bio_site_matrix, method = 'total') #

set.seed(1977128) # set seed to make sure the metaMDS repeats a best solution.
PISCO_bio_site_MDS1 <- metaMDS(PISCO_bio_site_matrix_decostand, distance = 'bray') # stress value should be between 0 and 0.2 according to https://jkzorz.github.io/2019/06/06/NMDS.html.# My stress value is 0.15

## reformat so it can be plotted in ggplot with groupings.
PISCO_bio_site_data_scores <- as.data.frame(scores(PISCO_bio_site_MDS1)$sites)

## Add back identifier columns
PISCO_bio_site_data_scores$transect_ID = unique(PISCO_bio_site$transect_ID) 

# i want to join this with the sites and dates and stuff.
PISCO_bio_site_years <- PISCO_bio_site %>%
  dplyr::select(transect_ID, year) # just these cols
dim(PISCO_bio_site_years) # check dimensions. 2037 rows. remove duplicates for the join.
PISCO_bio_site_years_distinct <- distinct(PISCO_bio_site_years)

PISCO_bio_site_NMDS_years <- dplyr::inner_join(PISCO_bio_site_data_scores, PISCO_bio_site_years_distinct, by = 'transect_ID')
# rownames(PISCO_bio_frc_matrix_decostand) = PISCO_bio_frc_NMDS_years$year

# Prepping the species vectors
spp_fit <- envfit(PISCO_bio_site_MDS1, PISCO_bio_site_matrix_decostand, permutations = 999) # there were 50+ warnings bc SD = 0.
spp_scores <- as.data.frame(scores(spp_fit, display = 'vectors'))
spp_scores <- cbind(spp_scores, species = rownames(spp_scores))
spp_scores <- cbind(spp_scores, pval = spp_fit$vectors$pvals)
sig_spp_scores <- subset(spp_scores, pval <= 0.05) %>% arrange(pval) # this is where it filters for P <= 0.05

# PERMANOVA
site_adonis <- adonis2(PISCO_bio_site_matrix_decostand ~ PISCO_bio_site_NMDS_years$year) # seems like bray-curtis is the default yay
# no need to nest transectID in site here because it's only for one site!!
onesite_disper <- betadisper(vegdist(PISCO_bio_site_matrix_decostand), PISCO_bio_site_NMDS_years$year) #***
anova(onesite_disper) # P = 0.1 but pls check.

# NMDS plot
## diverging color scheme
divergent <- c('skyblue', 'blue', 'navy', 'black')
ggplot(PISCO_bio_site_NMDS_years, aes(x = NMDS1, y = NMDS2, color = year)) +
  stat_ellipse() +
  annotate('text', x = 1.2, y = 0.85, label = paste('Stress =', round(PISCO_bio_site_MDS1$stress, digits = 3))) +
  annotate('text', x = 1.2, y = 0.75, label = paste('P =', site_adonis$`Pr(>F)`[1])) +
  # ggtitle('Swath and UPC community dissimilarities') +
  geom_segment(data = sig_spp_scores, aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), color = 'grey80', arrow = arrow(length = unit(0.2, "cm")), lwd = 0.3) +
  geom_point(size = 5, alpha = 0.7) +
  annotate('text', size = 3, x = sig_spp_scores$NMDS1, y = sig_spp_scores$NMDS2, label = sig_spp_scores$species, color = 'grey60') +
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12)) +
  scale_color_manual(values = divergent) +
  pres_theme

## SIMPER
PISCO_bio_site_simper <- simper(PISCO_bio_site_matrix_decostand, group = PISCO_bio_site_NMDS_years$year)
PISCO_bio_site_simper
summary(PISCO_bio_site_simper)

#look at SIMPER results with sig p values
comparisons <- c('2021_2022', '2021_2024', '2021_2025', '2022_2024', '2022_2025', '2024_2025')
PISCO_bio_site_simper_results <- simper.tidy(simper.summary.object = PISCO_bio_site_simper, comparisons = comparisons)

PISCO_bio_site_simper_results %>% 
  filter(Xp <= 0.05) %>% #dunno why there is an X in the col names
  arrange(desc(Xaverage))
  # count(Comparison) # which pair comparison has the most significant differences? maybe this pair are the most different.

```
# However, SIMPER doesn't indicate which group a species was more strongly associated with; see Indicator Species Analysis for that.
