---
title: "Reef Check California HOBO loggers"
subtitle: "By Gina Contolini. Greater Farallones Association, NOAA Affiliate"
author: "Greater Farallones and Cordell Bank National Marine Sanctuaries"
date: "Updated on `r Sys.Date()`"
header-includes:
- \usepackage{float}
- \floatplacement{figure}{H}
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(flextable)

theme_set(theme( 
   panel.background = element_rect(fill = 'transparent', color = NA_character_), # transparent panel background
   plot.background = element_rect(fill = 'transparent', color = NA_character_), #transparent plot bkgd
   panel.grid = element_line(color = 'transparent'), # remove all grid lines
   panel.border = element_blank(),
   axis.text = element_text(size = 13,color = 'black'), # makes axis labels bigger
   axis.title = element_text(size = 15), #makes axis title bigger and bold
   # axis.ticks.x = element_blank(),
   # axis.title.y = element_text(margin=margin(0,10,0,5)), # pushes the y axis title away from the y axis labels
   # axis.text.x = element_text(margin=margin(0,0,20,0)), #pushes the x axis title away from the x axis labels and pushes the bars down closer to the x axis labels
   legend.title = element_text(size = 16),
   legend.text = element_text(size = 16),
   legend.background = element_rect(fill = 'transparent', color = NA_character_),
   axis.line = element_line(color = 'black'),
   plot.title = element_text(size = 15),
   legend.key = element_blank(), # removes box around legend key
   axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)
))

```

# Stillwater Cove
```{r Stillwater Cove load and format data, include = FALSE}

# remove dates beyond deployments. 

rcca_swc_2017 <- read_csv("SWS_2017_09_Hobo.csv") %>% # has over 50,000 observations
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`, tz = 'America/Los_Angeles')) %>% # 8 failed to parse
  filter(datetime > ymd_hm('2017-09-17 16:00', tz = 'America/Los_Angeles') & datetime < ymd_hm('2017-08-02 12:25', tz = 'America/Los_Angeles'))

rcca_swc_2018_1 <- read_csv("SWS_2018_04_Hobo.csv") %>% # has only about 5,000 observations
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`, tz = 'America/Los_Angeles')) %>% 
  filter(datetime > ymd_hm('2018-04-18 15:02', tz = 'America/Los_Angeles') & datetime < ymd_hm('2018-09-14 16:55', tz = 'America/Los_Angeles'))

rcca_swc_2018_2 <- read_csv("SWS_2018_09_Hobo.csv") %>% # note 2019 data was lost
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`, tz = 'America/Los_Angeles')) %>% # 6 failed to parse
  filter(datetime > ymd_hm('2018-09-14 16:55', tz = 'America/Los_Angeles') & datetime < ymd_hm('2019-08-02 12:25', tz = 'America/Los_Angeles'))

rcca_swc_2020 <- read_csv("SWS_2020_10_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`, tz = 'UTC')) %>% 
  filter(datetime > ymd_hm('2020-10-09 10:12', tz = 'America/Los_Angeles') & datetime < ymd_hm('2021-08-14 10:30', tz = 'America/Los_Angeles'))

rcca_swc_2021 <- read_csv("SWS_2021_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`, tz = 'UTC')) %>% 
  filter(datetime > ymd_hm('2021-08-14 10:30', tz = 'America/Los_Angeles') & datetime < ymd_hm('2022-08-21 10:00', tz = 'America/Los_Angeles'))

rcca_swc_2022 <- read_csv("SWS_2022_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`, tz = 'UTC')) %>% 
  filter(datetime > ymd_hm('2022-08-21 11:30', tz = 'America/Los_Angeles') & datetime < ymd_hm('2023-08-19 10:38', tz = 'America/Los_Angeles'))

rcca_swc_2023 <-  read_csv("SWS_2023_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`, tz = 'UTC')) %>% 
  filter(datetime > ymd_hm('2023-08-19 10:38', tz = 'America/Los_Angeles') & datetime < ymd_hm('2024-09-22 11:30', tz = 'America/Los_Angeles'))

rcca_swc_hobo <- bind_rows(rcca_swc_2017, rcca_swc_2018_1, rcca_swc_2018_2, rcca_swc_2020, rcca_swc_2021, rcca_swc_2022, rcca_swc_2023) %>% 
  mutate(year = year(datetime)) %>% 
  mutate(month = month(datetime)) %>% 
  mutate(day = day(datetime))

glimpse(rcca_swc_hobo)
tz(rcca_swc_hobo$datetime) # it says the timezone is LA. So did it automatically change the GMT time from the 2020 data? Check the first 6 rows of the original 2020 data and compare to the first six rows of the combined data from 2020.
head(rcca_swc_2020) # starts at 17:15 on Oct 09 and this is GMT +0.
head(rcca_swc_hobo[which(rcca_swc_hobo$year == 2020),]) # starts at 10:15 on Oct 09. that's 7 hours behind. ok coooooool it seems like it automatically changes the times to the same timezone with the rowbind!!

```

```{r Stillwater Cove plot raw data to check it for outliers, include = FALSE}
# this takes a long time since there are millions of data points, so I commented it out until I need to see it again.

# ggplot(rcca_hobo, aes(x = datetime, y = temp_C)) +
#   geom_point(color = 'coral') +
#   scale_x_datetime(breaks = '6 months')
```

```{r swc plot temps}
rcca_swc_hobo_mean_daily <- rcca_swc_hobo %>% 
  group_by(year, month, day) %>% 
  summarise(mean_daily_temp = mean(temp_C, na.rm = T), sd_daily_temp = sd(temp_C), min_daily_temp = min(temp_C), max_daily_temp = max(temp_C), n = n()) %>% 
  mutate(date = ymd(paste(year, month, day, sep = '-')))

ggplot(rcca_swc_hobo_mean_daily, aes(x = date, y = mean_daily_temp)) +
  geom_errorbar(aes(ymin = mean_daily_temp - sd_daily_temp, ymax = mean_daily_temp + sd_daily_temp, width = 0), color = 'grey50') +
  geom_point() +
  scale_x_datetime(breaks = '4 months') +
  scale_y_continuous(limits = c(7.7, 17), breaks = seq(8, 17, 1)) +
  ggtitle("Stillwater Cove")

# monthly monthly means
rcca_swc_hobo %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  mutate(year = factor(year, levels = 2018:2024)) %>% 
  summarise(mean_temp = mean(temp_C), sd = sd(temp_C)) %>% 
  mutate(date = ymd(paste(year, month, 1))) %>% 
  ggplot(aes(x = date, y = mean_temp)) +
  geom_errorbar(aes(ymin = mean_temp - sd, ymax = mean_temp + sd, width = 0), color = 'grey60') +
  scale_x_date(breaks = '3 months') +
  geom_point() +
  geom_line() +
  ggtitle('Stillwater Cove Monthly Mean Temps')
```

# Fort Ross Cove
```{r Fort Ross Cove load and format data, include = FALSE}

# remove dates beyond deployments. 
rcca_frc_2019 <- read_csv("FTR_2019_08_Hobo.csv") %>% #52,000 observations
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2019-08-02 11:25', tz = 'America/Los_Angeles') & datetime < ymd_hm('2020-10-09 12:52', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20400694, SEN S/N: 20400694)`)

rcca_frc_2020 <- read_csv("FTR_2020_10_Hobo.csv") %>% #31,000 observation
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2020-10-09 12:52', tz = 'America/Los_Angeles') & datetime < ymd_hm('2021-08-28 10:29', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20919267, SEN S/N: 20919267)`)

rcca_frc_2021 <- read_csv("FTR_2021_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2021-08-28 10:29', tz = 'America/Los_Angeles') & datetime < ymd_hm('2022-09-10 10:42', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20400460, SEN S/N: 20400460)`)

rcca_frc_2022 <- read_csv("FTR_2022_09_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2022-09-10 10:42', tz = 'America/Los_Angeles') & datetime < ymd_hm('2023-09-23 10:15', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20338175, SEN S/N: 20338175)`)
  
rcca_frc_hobo <- bind_rows(rcca_frc_2019, rcca_frc_2020, rcca_frc_2021, rcca_frc_2022) %>% 
  mutate(datetime = with_tz(datetime, tzone = 'America/Los_Angeles')) %>% # show the time in Pacific Time, not GMT +0
  mutate(year = year(datetime)) %>% 
  mutate(month = month(datetime)) %>% 
  mutate(day = day(datetime))

glimpse(rcca_frc_hobo)

```

```{r frc plot temps}
rcca_frc_hobo_mean_daily <- rcca_frc_hobo %>% 
  group_by(year, month, day) %>% 
  summarise(mean_daily_temp = mean(temp_C, na.rm = T), sd_daily_temp = sd(temp_C), min_daily_temp = min(temp_C), max_daily_temp = max(temp_C), n = n()) %>% 
  mutate(date = ymd(paste(year, month, day, sep = '-')))

ggplot(rcca_frc_hobo_mean_daily, aes(x = date, y = mean_daily_temp)) +
  geom_errorbar(aes(ymin = mean_daily_temp - sd_daily_temp, ymax = mean_daily_temp + sd_daily_temp, width = 0), color = 'grey50') +
  geom_point() +
  scale_x_datetime(breaks = '4 months') +
  scale_y_continuous(limits = c(7.7, 17), breaks = seq(8, 17, 1)) +
  ggtitle("Fort Ross Cove")

# monthly monthly means
rcca_frc_hobo %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  mutate(year = factor(year, levels = 2018:2024)) %>% 
  summarise(mean_temp = mean(temp_C), sd = sd(temp_C)) %>% 
  mutate(date = ymd(paste(year, month, 1))) %>% 
  ggplot(aes(x = date, y = mean_temp)) +
  geom_errorbar(aes(ymin = mean_temp - sd, ymax = mean_temp + sd, width = 0), color = 'grey60') +
  scale_x_date(breaks = '3 months') +
  geom_point() +
  geom_line() +
  ggtitle('Fort Ross Cove Monthly Mean Temps')
```

# Ocean Cove
```{r Ocean Cove load and format data, include = FALSE}

# remove dates beyond deployments. 
rcca_oc_2018_05 <- read_csv("OCV_2018_05_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`, tz = 'America/Los_Angeles')) %>% 
  filter(datetime > ymd_hm('2018-05-15 14:20', tz = 'America/Los_Angeles') & datetime < ymd_hm('2018-07-29 10:30', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20219898, SEN S/N: 20219898)`)

rcca_oc_2018_07 <- read_csv("OCV_2018_07_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`, tz = 'America/Los_Angeles')) %>% 
  filter(datetime > ymd_hm('2018-07-29 10:30', tz = 'America/Los_Angeles') & datetime < ymd_hm('2019-08-02 09:50', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20400689, SEN S/N: 20400689)`) # 4 failed to parse

rcca_oc_2019 <- read_csv("OCV_2019_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2019-08-02 09:50', tz = 'America/Los_Angeles') & datetime < ymd_hm('2020-09-02 09:40', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20338171, SEN S/N: 20338171)`)

rcca_oc_2020 <- read_csv("OCV_2020_09_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2020-09-02 09:40', tz = 'America/Los_Angeles') & datetime < ymd_hm('2021-08-29 11:50', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20408782, SEN S/N: 20408782)`)

rcca_oc_2021 <- read_csv("OCV_2021_058_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2021-08-29 11:50', tz = 'America/Los_Angeles') & datetime < ymd_hm('2022-09-10 09:48', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20919270, SEN S/N: 20919270)`)

rcca_oc_2022 <- read_csv("OCV_2022_09_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2022-09-10 09:48', tz = 'America/Los_Angeles') & datetime < ymd_hm('2023-09-8 16:15', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 21462433, SEN S/N: 21462433)`)
  
rcca_oc_2023 <- read_csv("OCV_2023_09_HOBO.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2023-09-8 16:15', tz = 'America/Los_Angeles') & datetime < ymd_hm('2024-08-24 10:00', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 21751449, SEN S/N: 21751449)`)

rcca_oc_hobo <- bind_rows(rcca_oc_2018_05, rcca_oc_2018_07, rcca_oc_2019, rcca_oc_2020, rcca_oc_2021, rcca_oc_2022, rcca_oc_2023) %>% 
  mutate(year = year(datetime)) %>% 
  mutate(month = month(datetime)) %>% 
  mutate(day = day(datetime))

glimpse(rcca_oc_hobo) 
tz(rcca_oc_hobo$datetime) #America/Los_Angeles 

# Check the timezone with tz()
# Change what timezone is displayed with with_tz(datetime, tzone = 'America/Los_Angeles')

```

```{r oc plot temps}
rcca_oc_hobo_mean_daily <- rcca_oc_hobo %>% 
  group_by(year, month, day) %>% 
  summarise(mean_daily_temp = mean(temp_C, na.rm = T), sd_daily_temp = sd(temp_C), min_daily_temp = min(temp_C), max_daily_temp = max(temp_C), n = n()) %>% 
  mutate(date = ymd(paste(year, month, day, sep = '-')))

ggplot(rcca_oc_hobo_mean_daily, aes(x = date, y = mean_daily_temp)) +
  geom_errorbar(aes(ymin = mean_daily_temp - sd_daily_temp, ymax = mean_daily_temp + sd_daily_temp, width = 0), color = 'grey50') +
  geom_point() +
  scale_x_datetime(breaks = '4 months') +
  scale_y_continuous(limits = c(7.7, 17), breaks = seq(8, 17, 1)) +
  ggtitle("Ocean Cove")

# monthly monthly means
rcca_oc_hobo %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  mutate(year = factor(year, levels = 2018:2024)) %>% 
  summarise(mean_temp = mean(temp_C), sd = sd(temp_C)) %>% 
  mutate(date = ymd(paste(year, month, 1))) %>% # make a new date variable that is continuous so it plots lines
  ggplot(aes(x = date, y = mean_temp)) +
  geom_errorbar(aes(ymin = mean_temp - sd, ymax = mean_temp + sd, width = 0), color = 'grey60') +
  scale_x_date(breaks = '3 months') +
  geom_point() +
  geom_line() +
  ggtitle('Ocean Cove Monthly Mean Temps')
```

# Gerstle Cove
```{r Gerstle Cove load and format data, include = FALSE}

# remove dates beyond deployments. 
rcca_gc_2018 <- read_csv("GCV_2018_07_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT-07:00`)) %>% 
  filter(datetime > ymd_hm('2018-07-28 13:15', tz = 'America/Los_Angeles') & datetime < ymd_hm('2019-07-27 10:00', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20400700, SEN S/N: 20400700)`)

rcca_gc_2020 <- read_csv("GCV_2020_09_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2020-09-03 09:30', tz = 'America/Los_Angeles') & datetime < ymd_hm('2021-09-11 13:23', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20408788, SEN S/N: 20408788)`)

rcca_gc_2021 <- read_csv("GCV_2021_09_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2021-09-11 13:23', tz = 'America/Los_Angeles') & datetime < ymd_hm('2022-08-20 10:53', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20475915, SEN S/N: 20475915)`)

rcca_gc_2022 <- read_csv("GCV_2022_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2022-08-20 10:53', tz = 'America/Los_Angeles') & datetime < ymd_hm('2023-09-09 12:22', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 21477722, SEN S/N: 21477722)`)
  
rcca_gc_2023 <- read_csv("GCV_2023_09_HOBO.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2023-09-09 12:22', tz = 'America/Los_Angeles') & datetime < ymd_hm('2024-08-24 14:45', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 21751438, SEN S/N: 21751438)`)

rcca_gc_2024 <- read_csv("GCV_2024_08_Hobo.csv") %>% 
  mutate(datetime = mdy_hm(`Date Time, GMT+00:00`)) %>% 
  filter(datetime > ymd_hm('2024-08-24 14:45', tz = 'America/Los_Angeles') & datetime < ymd_hm('2025-08-23 11:11', tz = 'America/Los_Angeles')) %>% 
  rename(temp_C = `Temp, °C (LGR S/N: 20338178, SEN S/N: 20338178)`)

rcca_gc_hobo <- bind_rows(rcca_gc_2018, rcca_gc_2020, rcca_gc_2021, rcca_gc_2022, rcca_gc_2023, rcca_gc_2024) %>% 
  mutate(year = year(datetime)) %>% 
  mutate(month = month(datetime)) %>% 
  mutate(day = day(datetime)) %>% 
  mutate(datetime = with_tz(datetime, tzone = 'America/Los_Angeles'))

glimpse(rcca_gc_hobo)
tz(rcca_gc_hobo$datetime) # LA

```

```{r gc plot temps}
rcca_gc_hobo_mean_daily <- rcca_gc_hobo %>% 
  group_by(year, month, day) %>% 
  summarise(mean_daily_temp = mean(temp_C, na.rm = T), sd_daily_temp = sd(temp_C), min_daily_temp = min(temp_C), max_daily_temp = max(temp_C), n = n()) %>% 
  mutate(date = ymd(paste(year, month, day, sep = '-')))

ggplot(rcca_gc_hobo_mean_daily, aes(x = date, y = mean_daily_temp)) +
  geom_errorbar(aes(ymin = mean_daily_temp - sd_daily_temp, ymax = mean_daily_temp + sd_daily_temp, width = 0), color = 'grey50') +
  geom_point() +
  scale_x_datetime(breaks = '4 months') +
  scale_y_continuous(limits = c(7.7, 17), breaks = seq(8, 17, 1)) +
  ggtitle("Gerstle Cove")

# monthly monthly means
rcca_gc_hobo %>% 
  ungroup() %>% 
  group_by(year, month) %>% 
  mutate(year = factor(year, levels = 2018:2025)) %>% 
  summarise(mean_temp = mean(temp_C), sd = sd(temp_C)) %>% 
  mutate(date = ymd(paste(year, month, 1))) %>% 
  ggplot(aes(x = date, y = mean_temp)) +
  geom_errorbar(aes(ymin = mean_temp - sd, ymax = mean_temp + sd, width = 0), color = 'grey60') +
  scale_x_date(breaks = '3 months') +
  geom_point() +
  geom_line() +
  ggtitle('Gerstle Cove Monthly Mean Temps')
#newline
```