---
title: "Subtidal Urchin Removals"
subtitle: "by Gina Contolini. Gina.Contolini@noaa.gov"
author: "Greater Farallones Association and Greater Farallones and Cordell Bank National Marine Sanctuaries"
date: "Updpated on `r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
# the shortcut for pipe is ctrl+shift+M

# something weird is going on because I can't get any of the packages to load. I keep starting a brand new project and it immediately tells me I need some packages installed or updated, and then it tells me to restart R, and immediately after I restart R is tells me the same message in an endless loop. 

#### Install and load packages ####
if(!require(car)){install.packages("car")}; library(car) # companion to applied regression
if(!require(ggpubr)){install.packages("ggpubr")}; library(ggpubr) # plot aesthetics
# if(!require(devtools)){install.packages("devtools")}; library(devtools)
if(!require(tidyverse)){install.packages("tidyverse")}; library(tidyverse) # all tidyverse packages including tidyr, dplyr, and ggplot2
if(!require(Rmisc)){install.packages("Rmisc")}; library(Rmisc) # for summarySE() summary stats function
if(!require(kableExtra)){install.packages("kableExtra")}; library(kableExtra)
# if(!require(vegan)){install.packages("vegan")}; library(vegan) # community ecology package
library(tinytex)

#### Create standard error function ####
se <- function(x){
   sd(x) / sqrt(length(x))
}

#### Create plot theme ####
theme_set(theme( 
   panel.background = element_blank(), # remove panel background
   # panel.grid.minor.x = element_blank(), # remove minor x axis grid line
   # panel.grid.major.x = element_blank(), # remove major x axis grid line
   panel.grid = element_blank(), # remove all grid lines
   axis.text = element_text(size = 13,color = 'black'), #makes axis labels bigger
   axis.title = element_text(size = 15), #makes axis title bigger and bold
   # axis.title.y = element_text(margin=margin(0,10,0,5)), #pushes the y axis title away from the y axis labels
   # axis.text.x = element_text(margin=margin(0,0,20,0)), #pushes the x axis title away from the x axis labels and pushes the bars down closer to the x axis labels
   legend.title = element_text(size = 16),
   legend.text = element_text(size = 16),
   legend.background = element_blank(),
   panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5), # border around the whole plot
   plot.title = element_text(size = 15),
   legend.key = element_blank()
))
```

```{r load in data}
landings <- read_csv('Purple urchin landings datasheets - landings_entry.csv')
```

```{pounds and number by site}
# Total pounds landed by site
# Total approx number landed by site

landings_totals <- landings %>%
  dplyr::group_by(site) %>%
  dplyr::summarize(total.lbs = sum(lbs_urchins), total.number = sum(number_urchins_calculated), n = n())

kbl(landings_totals)

```

These analyses were done using RMarkdown in RStudio v. 4.3.1. using R v. 4.3.1.